### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jan-gazda** [XITASO/atlassian-crowd-formula#1]
Hello I'm trying to write my own salt formula to deploy crowd and using your repo as an inspiration.

how ever I have few questions I could not google.

For example this:
```
crowd-server-xsl:
  file.managed:
    - name: /tmp/crowd-server.xsl
    - source: salt://atlassian-crowd/files/server.xsl
    - template: jinja
    - require:
      - file: crowd-install

  cmd.run:
    - name: 'xsltproc --stringparam pHttpPort "{{ crowd.get('http_port', '') }}" --stringparam pHttpScheme "{{ crowd.get('http_scheme', '') }}" --stringparam pHttpProxyName "{{ crowd.get('http_proxyName', '') }}" --stringparam pHttpProxyPort "{{ crowd.get('http_proxyPort', '') }}" --stringparam pAjpPort "{{ crowd.get('ajp_port', '') }}" -o /tmp/crowd-server.xml /tmp/crowd-server.xsl server.xml'
    - cwd: {{ crowd.dirs.install }}/apache-tomcat/conf
    - require:
      - file: crowd-server-xsl
```

What is and how does work:
```
    - require:
      - file: crowd-server-xsl
```
Because `crowd-server-xsl` is not a real file but state, same with `crowd-install`.

Another questions is why is it better to use `xsl` instead of templating existing `server.xml`?

I'd appreciate you could give me some hints and point to the docs.

Thank you!
